<template>
	<popup-shell headline="Import characters" acceptText="Browse" @accept="accept" @cancel="cancel">
		<span>You can import characters from a JSON file generated by <a href="https://github.com/Andrewthe13th/Inventory_Kamera" target="_blank">Inventory Kamera</a>.</span>
		<span class="error">{{ error }}</span>
		<input type="file" hidden accept="application/json" ref="fileInput" @change="handleImport">
	</popup-shell>
</template>

<script setup>
	import { ref } from "vue"
	import { useStore } from "vuex"
	import PopupShell from "../PopupShell.vue"

	const emit = defineEmits(["abort"])
	const store = useStore()

	const error = ref("")
	const fileInput = ref(null)

	const errors = {
		badFormat: "Selected file is in a wrong format.",
		noCharacters: "Selected file has no characters data."
	}

	function cancel() {
		emit("abort")
	}

	function accept() {
		fileInput.value.click()
	}

	function handleImport() {
		const file = fileInput.value?.files[0]
		const reader = new FileReader()

		if ("application/json" !== file?.type) {
			error.value = errors.badFormat
			return
		}

		reader.onload = (e) => {
			const data = JSON.parse(e.target.result)

			if ("GOOD" !== data.format || 1 !== data.version) {
				error.value = errors.badFormat
				return
			}

			if (!data.characters) {
				error.value = errors.noCharacters
				return
			}

			store.commit("importGOOD", data.characters)
			emit("abort")
		}

		reader.readAsText(fileInput.value?.files[0])
	}
</script>

<style scoped>
	.error {
		color: brown;
	}
</style>
