<template>
	<popup-shell headline="Import characters">
		<div class="row">
			You can import characters from a file generated by <a href="https://github.com/Andrewthe13th/Inventory_Kamera" target="_blank">Inventory Kamera</a>
		</div>
		<div class="row">
			<input type="file" accept="application/json" ref="fileInput">
		</div>
		<div class="row">
			<button @click="cancel">Cancel</button>
			<button @click="accept">Import</button>
		</div>
	</popup-shell>
</template>

<script setup>
	import { defineEmits, ref } from "vue"
	import { useStore } from "vuex"
	import PopupShell from "../PopupShell.vue"

	const emit = defineEmits(["abort"])
	const store = useStore()

	const fileInput = ref(null)

	function cancel() {
		emit("abort")
	}

	function accept() {
		try {
			const reader = new FileReader()

			reader.onload = (e) => {
				const data = JSON.parse(e.target.result)

				if ("GOOD" !== data.format || 1 !== data.version) {
					throw "Wrong file format"
				}

				store.commit("importGOOD", data.characters || [])
			}

			reader.readAsText(fileInput.value?.files[0])
		} catch (err) {
			// Ignore errors
		}

		emit("abort")
	}
</script>

<style scoped>
	.row {
		display: flex;
		justify-content: center;
		gap: 1em;
	}
</style>
