<template>
	<popup-shell headline="Import characters">
		<div class="row">
			<span>You can import characters from a JSON file generated by <a href="https://github.com/Andrewthe13th/Inventory_Kamera" target="_blank">Inventory Kamera</a>.</span>
		</div>
		<input type="file" hidden accept="application/json" ref="fileInput" @change="handleImport">
		<div class="row">
			<button @click="cancel">Cancel</button>
			<button @click="accept">Browse</button>
		</div>
	</popup-shell>
</template>

<script setup>
	import { defineEmits, ref } from "vue"
	import { useStore } from "vuex"
	import PopupShell from "../PopupShell.vue"

	const emit = defineEmits(["abort"])
	const store = useStore()

	const fileInput = ref(null)

	function cancel() {
		emit("abort")
	}

	function accept() {
		fileInput.value.click()
	}

	function handleImport() {
		try {
			const reader = new FileReader()

			reader.onload = (e) => {
				const data = JSON.parse(e.target.result)

				if ("GOOD" !== data.format || 1 !== data.version) {
					throw "Wrong file format"
				}

				if (!data.characters) {
					throw "No characters data"
				}

				store.commit("importGOOD", data.characters)
				emit("abort")
			}

			reader.readAsText(fileInput.value?.files[0])
		} catch (err) {
			// Ignore errors
		}
	}
</script>

<style scoped>
	.row {
		display: flex;
		justify-content: center;
		gap: 1em;
	}
</style>
