<template>
	<main>
		<p>
			First, select as many characters that you own as possible by
			clicking their portraits. Alternatively, you can import characters
			from a JSON file generated by
			<a
				href="https://github.com/Andrewthe13th/Inventory_Kamera"
				target="_blank"
			>
				Inventory Kamera.
			</a>
		</p>
		<p>
			After selecting at least 5 characters, click the button at the
			bottom of the page to continue to party creation. You may return to
			this step anytime later.
		</p>
		<div id="character-pool">
			<div
				v-for="char in characters"
				:key="char"
				:class="{
					owned: userData.ownedCharacters[char] !== undefined,
				}"
			>
				<CharacterCard
					:characterId="char"
					:cursor="'pointer'"
					@click="() => selectCharacter(char)"
				/>
				<div class="constellation-overlay">
					C{{ userData.ownedCharacters[char]?.constellation }}
				</div>
			</div>
		</div>
		<button @click="() => (activePopup = { type: 'import' })">
			Import
		</button>
		<button @click="nextStage" v-if="shouldShowNextButton">Next</button>
	</main>
	<ImportPopup v-if="'import' === activePopup.type" @abort="closePopup" />
	<ConstellationPopup
		:characterId="activePopup.data"
		@abort="closePopup"
		v-else-if="'constellation' === activePopup.type"
	/>
</template>

<script setup>
	import { ref, computed, onBeforeUnmount } from "vue"
	import { useAPI } from "@/hooks/api"
	import { useHead } from "@vueuse/head"
	import { useJsonDataStore } from "@/stores/jsonData"
	import { useRouter } from "vue-router"
	import { useUserDataStore } from "@/stores/userData"
	import CharacterCard from "@/components/CharacterCard"
	import ConstellationPopup from "@/components/popups/ConstellationPopup"
	import ImportPopup from "@/components/popups/ImportPopup"

	const { fetchData } = useAPI()
	const jsonData = useJsonDataStore()
	const router = useRouter()
	const userData = useUserDataStore()
	useHead({ title: `My characters | ${process.env.VUE_APP_SITE_NAME}` })

	fetchData()

	const activePopup = ref({ type: null, data: null })

	const characters = computed(() => {
		return Object.keys(jsonData.characters)
	})

	const shouldShowNextButton = computed(() => {
		return Object.keys(userData.ownedCharacters).length >= 5
	})

	function nextStage() {
		router.push({ name: "parties" })
	}

	function selectCharacter(characterId) {
		activePopup.value = { type: "constellation", data: characterId }
	}

	function closePopup() {
		activePopup.value = { type: null }
	}

	function hotkeyHandler(e) {
		if (null !== activePopup.value.type) return

		if (shouldShowNextButton.value) {
			if (e.key === "Enter" || e.key === "Escape") {
				nextStage()
			}
		}
	}

	window.addEventListener("keydown", hotkeyHandler)

	onBeforeUnmount(() => {
		window.removeEventListener("keydown", hotkeyHandler)
	})
</script>

<style lang="scss" scoped>
	main {
		#character-pool {
			margin: 1em 0;
			display: flex;
			flex-flow: wrap;
			gap: 1em;
			justify-content: center;

			& > div {
				position: relative;

				&:not(.owned) {
					filter: saturate(0.25);

					.constellation-overlay {
						display: none;
					}
				}

				.constellation-overlay {
					background-color: var(--button-background-color);
					pointer-events: none;
					z-index: 5;

					position: absolute;
					bottom: 1.3rem;
					height: 1em;
					width: 5rem;
					padding: 0.25em 0;

					color: var(--button-font-color);
					font-family: Hoyofont;
					font-size: 0.8rem;
					text-align: center;
				}
			}
		}
	}
</style>
