<template>
	<main>
		<p>
			First, select as many characters that you own as possible by
			clicking their portraits. Alternatively, you can import them from a
			JSON file in GOOD format. It can be automatically generated by
			<a
				href="https://github.com/Andrewthe13th/Inventory_Kamera"
				target="_blank"
			>
				Inventory Kamera
			</a>
			or a similar tool.
		</p>
		<p>
			After selecting at least 5 characters, click the «Next» button at the
			bottom of the page to continue to party creation. You may return to
			this step anytime later.
		</p>
		<div id="character-pool">
			<CharacterCard
				:characterId="char"
				:cursor="'pointer'"
				:key="char"
				:owned="Boolean(userData.ownedCharacters[char])"
				@click="() => selectCharacter(char)"
				v-for="char in characters"
			/>
		</div>
		<div class="button-wrapper">
			<button @click="() => activePopup = { type: 'import' }">
				Import
			</button>
			<button @click="nextStage" v-if="shouldShowNextButton">
				Next
			</button>
		</div>
	</main>
	<ImportPopup v-if="'import' === activePopup.type" @abort="closePopup" />
	<ConstellationPopup
		:characterId="activePopup.data"
		@abort="closePopup"
		v-else-if="'constellation' === activePopup.type"
	/>
</template>

<script setup>
	import { ref, computed, onBeforeUnmount } from "vue"
	import { useHead } from "@vueuse/head"
	import { useJsonDataStore } from "@/stores/jsonData"
	import { useRouter } from "vue-router"
	import { useUserDataStore } from "@/stores/userData"
	import CharacterCard from "@/components/CharacterCard"
	import ConstellationPopup from "@/components/ConstellationPopup"
	import ImportPopup from "@/components/ImportPopup"

	const jsonData = useJsonDataStore()
	const router = useRouter()
	const userData = useUserDataStore()
	useHead({ title: `My characters | ${process.env.VUE_APP_SITE_NAME}` })

	jsonData.sync()

	const activePopup = ref({ type: null, data: null })

	const characters = computed(() => Object.keys(jsonData.characters))

	const shouldShowNextButton = computed(
		() => Object.keys(userData.ownedCharacters).length >= 5
	)

	function nextStage() {
		router.push({ name: "parties" })
	}

	function selectCharacter(characterId) {
		activePopup.value = { type: "constellation", data: characterId }
	}

	function closePopup() {
		activePopup.value = { type: null }
	}

	function hotkeyHandler(e) {
		if (null !== activePopup.value.type) {
			return
		}

		if (shouldShowNextButton.value) {
			if (e.key === "Enter" || e.key === "Escape") {
				nextStage()
			}
		}
	}

	window.addEventListener("keydown", hotkeyHandler)
	onBeforeUnmount(() => {
		window.removeEventListener("keydown", hotkeyHandler)
	})
</script>

<style scoped>
	main {
		margin-top: 1em;
	}

	#character-pool {
		display: flex;
		flex-flow: wrap;
		gap: 0.5em;
		margin: 0.5em;
		width: inherit;
	}
</style>
