<template>
	<div id="dialogue-wrapper">
		<div id="import-dialogue">
			<h2>
				Import characters
			</h2>
			<div class="row">
				You can import characters from a file generated by <a href="https://github.com/Andrewthe13th/Inventory_Kamera" target="_blank">Inventory Kamera</a>
			</div>
			<div class="row">
				<input type="file" accept="application/json" ref="fileInput">
			</div>
			<div class="row">
				<button @click="cancel">Cancel</button>
				<button @click="accept">Import</button>
			</div>
		</div>
	</div>
</template>

<script setup>
	import { defineEmits, ref } from "vue"
	import { useStore } from "vuex"

	const emit = defineEmits(["abort"])

	const fileInput = ref(null)

	const store = useStore()

	function cancel() {
		emit("abort")
	}

	function accept() {
		try {
			const reader = new FileReader()

			reader.onload = (e) => {
				const data = JSON.parse(e.target.result)

				if ("GOOD" !== data.format || 1 !== data.version) {
					throw "Wrong file format"
				}

				store.commit("importGOOD", data.characters || [])
			}

			reader.readAsText(fileInput.value?.files[0])
		} catch (err) {
			// Ignore errors
		}

		emit("abort")
	}
</script>

<style lang="scss" scoped>
	#dialogue-wrapper {
		position: fixed;
		bottom: 0;
		left: 0;
		right: 0;
		top: 0;

		display: flex;
		justify-content: center;
		align-items: center;
		z-index: 10;

		background-color: #1117;
	}

	#import-dialogue {
		background-color: #1c1c1c;
		padding: 1em;
		display: flex;
		flex-direction: column;
		gap: 1em;
		border-radius: 0.5em;

		h2 {
			margin: 0;
		}
	}

	.row {
		display: flex;
		justify-content: center;
		gap: 1em;
	}
</style>
